"""
services/report_service.py
============================
MODULE 5 — Incident report PDF generation.

Builds a downloadable "Accidental Maritime Boundary Crossing Report" for
a given boat using ReportLab, pulling in the boat's latest known
alert/incident info, weather conditions, and full event timeline.
"""

from __future__ import annotations

import logging
import os
import tempfile
from datetime import datetime, timezone
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from database import get_incident_events
from services.weather_service import get_weather

logger = logging.getLogger("seasentry.report_service")

ASSESSMENT_TEXT = (
    "Based on the available vessel position and environmental conditions, "
    "this report indicates that the vessel appears to have crossed the "
    "maritime boundary unintentionally due to environmental drift. This "
    "document is automatically generated by SeaSentry AI for emergency "
    "reporting purposes."
)

NOT_AVAILABLE = "Not Available"


def _build_styles() -> dict:
    """Return a dict of ParagraphStyles used throughout the report."""
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "ReportTitle", parent=base["Title"], fontSize=18, spaceAfter=4,
        ),
        "subtitle": ParagraphStyle(
            "ReportSubtitle", parent=base["Normal"], fontSize=12,
            textColor=colors.HexColor("#333333"), spaceAfter=16,
        ),
        "section_header": ParagraphStyle(
            "SectionHeader", parent=base["Heading2"], fontSize=13,
            spaceBefore=14, spaceAfter=6, textColor=colors.HexColor("#0B3D91"),
        ),
        "body": ParagraphStyle(
            "Body", parent=base["Normal"], fontSize=10, leading=14,
        ),
        "footer": ParagraphStyle(
            "Footer", parent=base["Normal"], fontSize=8,
            textColor=colors.HexColor("#777777"), alignment=1,
        ),
    }


def _latest_alert_info(boat_id: str) -> dict:
    """
    Derive alert type / reason / timestamp / lat / lon for a boat from
    its recorded incident events (most recent SOS/alert-related event).
    """
    events = get_incident_events(boat_id)

    alert_type = NOT_AVAILABLE
    reason = NOT_AVAILABLE
    timestamp: Optional[datetime] = None

    for event in reversed(events):
        if event.event_type.startswith("ALERT_CREATED_"):
            alert_type = event.event_type.replace("ALERT_CREATED_", "")
            reason = event.description
            timestamp = event.timestamp
            break

    return {
        "alert_type": alert_type,
        "reason": reason,
        "timestamp": timestamp,
    }


def generate_incident_report_pdf(
    boat_id: str,
    latitude: Optional[float] = None,
    longitude: Optional[float] = None,
) -> str:
    """
    Generate the incident report PDF for a boat and return the file path.

    Args:
        boat_id: Unique identifier of the boat.
        latitude: Last known latitude (used for weather lookup + report).
        longitude: Last known longitude (used for weather lookup + report).

    Returns:
        Absolute path to the generated PDF file on disk.
    """
    logger.info("Generating incident report PDF for boat_id=%s", boat_id)

    styles = _build_styles()
    alert_info = _latest_alert_info(boat_id)
    events = get_incident_events(boat_id)

    incident_time = alert_info["timestamp"] or datetime.now(timezone.utc)
    lat_display = latitude if latitude is not None else NOT_AVAILABLE
    lon_display = longitude if longitude is not None else NOT_AVAILABLE

    weather = None
    if latitude is not None and longitude is not None:
        weather = get_weather(latitude, longitude)

    wind_speed = weather["wind_speed"] if weather else NOT_AVAILABLE
    wind_direction = weather["wind_direction"] if weather else NOT_AVAILABLE
    temperature = weather["temperature"] if weather else NOT_AVAILABLE

    tmp_dir = tempfile.gettempdir()
    output_path = os.path.join(tmp_dir, f"seasentry_report_{boat_id}.pdf")

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
    )

    story = []

    # --- Title ---------------------------------------------------------
    story.append(Paragraph("SeaSentry AI", styles["title"]))
    story.append(Paragraph("Accidental Maritime Boundary Crossing Report", styles["subtitle"]))

    # --- Boat Information ------------------------------------------------
    story.append(Paragraph("Boat Information", styles["section_header"]))
    boat_table_data = [
        ["Boat ID", boat_id],
        ["Incident Time", incident_time.isoformat()],
        ["Latitude", str(lat_display)],
        ["Longitude", str(lon_display)],
    ]
    story.append(_make_table(boat_table_data))

    # --- Alert Information -----------------------------------------------
    story.append(Paragraph("Alert Information", styles["section_header"]))
    alert_table_data = [
        ["Alert Type", str(alert_info["alert_type"])],
        ["Reason", str(alert_info["reason"])],
        ["Timestamp", incident_time.isoformat() if alert_info["timestamp"] else NOT_AVAILABLE],
    ]
    story.append(_make_table(alert_table_data))

    # --- Weather -----------------------------------------------------------
    story.append(Paragraph("Weather", styles["section_header"]))
    weather_table_data = [
        ["Wind Speed", wind_speed],
        ["Wind Direction", wind_direction],
        ["Temperature", temperature],
    ]
    story.append(_make_table(weather_table_data))

    # --- Assessment ----------------------------------------------------
    story.append(Paragraph("Assessment", styles["section_header"]))
    story.append(Paragraph(ASSESSMENT_TEXT, styles["body"]))

    # --- Timeline ------------------------------------------------------
    story.append(Paragraph("Timeline", styles["section_header"]))
    if events:
        timeline_data = [["Timestamp", "Event", "Description"]]
        for event in sorted(events, key=lambda e: e.timestamp):
            timeline_data.append([
                event.timestamp.isoformat(),
                event.event_type,
                event.description,
            ])
        story.append(_make_table(timeline_data, header=True))
    else:
        story.append(Paragraph("No recorded events for this boat.", styles["body"]))

    story.append(Spacer(1, 24))
    story.append(Paragraph("Automatically generated by SeaSentry AI.", styles["footer"]))

    doc.build(story)
    logger.info("Incident report PDF generated at %s", output_path)
    return output_path


def _make_table(data: list, header: bool = False) -> Table:
    """Build a consistently styled ReportLab Table from row data."""
    table = Table(data, hAlign="LEFT", colWidths=None)
    style_commands = [
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]
    if header:
        style_commands += [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0B3D91")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ]
    else:
        style_commands += [
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ]
    table.setStyle(TableStyle(style_commands))
    return table
